### ISSUE TITLE
ncdf4 appears under both Suggests and Imports in DESCRIPTION

### ISSUE THREAD

**Issue by andrewdolman** [EarthSystemDiagnostics/ecustools#6]
ncdf4 appears under both Suggests and Imports in DESCRIPTION. Should just be Suggests.

Add the following to GetNetCDFAtCoords and remove from Imports

 if (!requireNamespace("ncdf4", quietly = TRUE)) {
    stop("package 'ncdf4' is needed for this function to work. Please install it.",
         call. = FALSE)
  }

**Comment by andrewdolman** [comment]
Should also add comment that netcdf libraries need to be installed before ncdf4

**Comment by thomas-muench** [comment]
Closed by #7.
